### ISSUE TITLE
HALT input signal.

### ISSUE THREAD

**Issue by srg320** [ijor/fx68k#1]
Will support for the HALT input signal and RESET/HALT signals combination be added?

**Comment by jotego** [comment]
I'd also like to see support for this.

**Comment by srg320** [comment]
Logs of single-step mode HALT in sub cpu in real SegaCD. Maybe this information will help somehow.

![dma_pcm](https://user-images.githubusercontent.com/40274294/69316951-8790a580-0c42-11ea-891d-c9d6cbb7cb93.jpg)
![dma_prgram](https://user-images.githubusercontent.com/40274294/69316965-8e1f1d00-0c42-11ea-89e9-8a293b90cc5f.jpg)

**Comment by ijor** [comment]
Thanks. It is helpful and it confirms the theory. Support for HALT single step coming soon ...

**Comment by ijor** [comment]
Commited support for HALT single step
