### ISSUE TITLE
subq instruction bug

### ISSUE THREAD

**Issue by jotego** [ijor/fx68k#9]
The subq instruction in the code:

![image](https://user-images.githubusercontent.com/1863036/120321247-5edf7680-c2e3-11eb-8361-2acc5ef5424a.png)

is not executed correctly by fx68k. Look at the following signal dump:

![image](https://user-images.githubusercontent.com/1863036/120321335-7a4a8180-c2e3-11eb-9218-6074e6a8b233.png)

The CPU has to read the value in memory address $FFF310, decreased it by one and write it back. The value read is $8401, but the value written back **is $0000** instead of $8400.

This is how the same instructions look like through the J68_CPU module, to serve as a reference:

![image](https://user-images.githubusercontent.com/1863036/120322208-7408d500-c2e4-11eb-9f29-7dfe32f0bf24.png)

You can see how the ram_data bus is decreased by one in this case.

Could you please look into this bug?

**Comment by ijor** [comment]
Jose,

You are performing a byte sized instruction. It is not $8401 - 1, it is $01 - 1. So the result is $00, and not $8400.

Also the FX68K behavior is correct. When performing a byte sized write, the byte data is replicated in the other half of the 16 bits data bus. That's what a real 68000 does and it is documented in Motorola hardware manual.

**Comment by jotego** [comment]
You're right. I'm back to square 1 then. I'll keep looking.
